// lib/data.js

export const translations = {
  az: {
    nav: {
      home: 'Ana Səhifə',
      masters: 'Ustalar',
      services: 'Avtoservislər',
      categories: 'Xidmətlər',
      shops: 'Mağazalar',
      blog: 'Blog',
      allMasters: 'Bütün Ustalar',
      allServices: 'Bütün Servislər',
      business: 'Biznes ol',
    },
    hero: {
      badge: 'Azərbaycanın №1 Avto Platforması',
      title: 'Avtomobiliniz üçün',
      titleHighlight: 'hər şey bir yerdə',
      subtitle: 'Ən yaxın ustaları, avtoservislər, ehtiyat hissələri mağazaları — hamısı bir platformada. Tap, əlaqə qur, xidmət al.',
      search: 'Usta, servis, mağaza axtar...',
      searchBtn: 'Axtar',
      ctaExplore: 'Kəşf Et',
      ctaLearn: 'Necə işləyir?',
    },
    stats: {
      users: 'İstifadəçi',
      masters: 'Usta',
      services: 'Avtoservis',
      shops: 'Mağaza',
    },
    sections: {
      featuredMasters: 'Öne Çıxan Ustalar',
      featuredMastersDesc: 'Ən çox tövsiyə edilən peşəkar ustalar',
      featuredServices: 'Öne Çıxan Servislər',
      featuredServicesDesc: 'Bölgənizdəki ən yaxşı avtoservislər',
      categories: 'Xidmət Kateqoriyaları',
      categoriesDesc: 'Ehtiyacınıza görə xidmət tapın',
      viewAll: 'Hamısına Bax',
      howItWorks: 'Necə İşləyir',
      howDesc: 'Üç sadə addımda başlayın',
      step1Title: 'Axtar',
      step1Desc: 'Xidmət, usta və ya mağaza axtar',
      step2Title: 'Seç',
      step2Desc: 'Reytinq və rəylərə baxaraq seç',
      step3Title: 'Əlaqə Qur',
      step3Desc: 'Birbaşa zəng et və ya mesaj göndər',
      testimonials: 'İstifadəçi Rəyləri',
      testimonialsDesc: 'Minlərlə sürücü artıq güvənir',
      brandsTitle: 'Dəstəklədiyimiz Markalar',
      brands: 'BMW · Mercedes · Toyota · Honda · Hyundai · Kia · Volkswagen · Audi · Ford · Chevrolet · Nissan · Lexus',
    },
    footer: {
      desc: 'Avtomobiliniz üçün ehtiyac duyduğunuz hər şey — ustalar, servislər, mağazalar — hamısı bir platformada.',
      links: 'Sürətli Keçidlər',
      contact: 'Əlaqə',
      rights: 'Bütün hüquqlar qorunur.',
      address: 'Bakı, Azərbaycan',
    },
    cards: {
      rating: 'reytinq',
      reviews: 'rəy',
      call: 'Zəng Et',
      details: 'Ətraflı',
      open: 'Açıqdır',
      closed: 'Qapalıdır',
      readMore: 'Oxu',
    }
  },
  ru: {
    nav: {
      home: 'Главная',
      masters: 'Мастера',
      services: 'Автосервисы',
      categories: 'Услуги',
      shops: 'Магазины',
      blog: 'Блог',
      allMasters: 'Все мастера',
      allServices: 'Все сервисы',
      business: 'Стать бизнесом',
    },
    hero: {
      badge: 'Авто платформа №1 в Азербайджане',
      title: 'Всё для вашего',
      titleHighlight: 'автомобиля в одном месте',
      subtitle: 'Ближайшие мастера, автосервисы, магазины запчастей — всё на одной платформе. Найди, свяжись, получи услугу.',
      search: 'Поиск мастеров, сервисов, магазинов...',
      searchBtn: 'Найти',
      ctaExplore: 'Исследовать',
      ctaLearn: 'Как это работает?',
    },
    stats: {
      users: 'Пользователей',
      masters: 'Мастеров',
      services: 'Автосервисов',
      shops: 'Магазинов',
    },
    sections: {
      featuredMasters: 'Топ мастера',
      featuredMastersDesc: 'Самые рекомендуемые профессионалы',
      featuredServices: 'Топ сервисы',
      featuredServicesDesc: 'Лучшие автосервисы в вашем районе',
      categories: 'Категории услуг',
      categoriesDesc: 'Найдите услугу по вашим потребностям',
      viewAll: 'Смотреть все',
      howItWorks: 'Как это работает',
      howDesc: 'Начните в три простых шага',
      step1Title: 'Ищите',
      step1Desc: 'Найдите услугу, мастера или магазин',
      step2Title: 'Выбирайте',
      step2Desc: 'Выберите по рейтингу и отзывам',
      step3Title: 'Свяжитесь',
      step3Desc: 'Позвоните напрямую или отправьте сообщение',
      testimonials: 'Отзывы пользователей',
      testimonialsDesc: 'Тысячи водителей уже доверяют нам',
      brandsTitle: 'Поддерживаемые марки',
      brands: 'BMW · Mercedes · Toyota · Honda · Hyundai · Kia · Volkswagen · Audi · Ford · Chevrolet · Nissan · Lexus',
    },
    footer: {
      desc: 'Всё необходимое для вашего автомобиля — мастера, сервисы, магазины — всё на одной платформе.',
      links: 'Быстрые ссылки',
      contact: 'Контакты',
      rights: 'Все права защищены.',
      address: 'Баку, Азербайджан',
    },
    cards: {
      rating: 'рейтинг',
      reviews: 'отзывов',
      call: 'Позвонить',
      details: 'Подробнее',
      open: 'Открыто',
      closed: 'Закрыто',
      readMore: 'Читать',
    }
  },
  en: {
    nav: {
      home: 'Home',
      masters: 'Masters',
      services: 'Auto Services',
      categories: 'Services',
      shops: 'Shops',
      blog: 'Blog',
      allMasters: 'All Masters',
      allServices: 'All Services',
      business: 'Become a Business',
    },
    hero: {
      badge: "Azerbaijan's #1 Auto Platform",
      title: 'Everything for your',
      titleHighlight: 'car in one place',
      subtitle: 'Nearest masters, auto services, spare parts shops — all on one platform. Find, connect, get service.',
      search: 'Search masters, services, shops...',
      searchBtn: 'Search',
      ctaExplore: 'Explore',
      ctaLearn: 'How it works?',
    },
    stats: {
      users: 'Users',
      masters: 'Masters',
      services: 'Auto Services',
      shops: 'Shops',
    },
    sections: {
      featuredMasters: 'Featured Masters',
      featuredMastersDesc: 'Most recommended professional masters',
      featuredServices: 'Featured Services',
      featuredServicesDesc: 'Best auto services in your area',
      categories: 'Service Categories',
      categoriesDesc: 'Find the service you need',
      viewAll: 'View All',
      howItWorks: 'How It Works',
      howDesc: 'Get started in three simple steps',
      step1Title: 'Search',
      step1Desc: 'Search for a service, master or shop',
      step2Title: 'Choose',
      step2Desc: 'Select based on ratings and reviews',
      step3Title: 'Connect',
      step3Desc: 'Call directly or send a message',
      testimonials: 'User Reviews',
      testimonialsDesc: 'Thousands of drivers already trust us',
      brandsTitle: 'Supported Brands',
      brands: 'BMW · Mercedes · Toyota · Honda · Hyundai · Kia · Volkswagen · Audi · Ford · Chevrolet · Nissan · Lexus',
    },
    footer: {
      desc: 'Everything your car needs — masters, services, shops — all on one platform.',
      links: 'Quick Links',
      contact: 'Contact',
      rights: 'All rights reserved.',
      address: 'Baku, Azerbaijan',
    },
    cards: {
      rating: 'rating',
      reviews: 'reviews',
      call: 'Call',
      details: 'Details',
      open: 'Open',
      closed: 'Closed',
      readMore: 'Read',
    }
  }
}

export const masters = [
  {
    id: 1,
    name: 'Rəşad Əliyev', nameRu: 'Рашад Алиев', nameEn: 'Rashad Aliyev',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    categories: { az: ['Motor Təmiri', 'Diaqnostika'], ru: ['Ремонт двигателя', 'Диагностика'], en: ['Engine Repair', 'Diagnostics'] },
    address: { az: 'Nərimanov r., Bakı', ru: 'Нариманов р-н, Баку', en: 'Narimanov dist., Baku' },
    rating: 4.9, reviews: 127, isOpen: true, phone: '+994 50 123 45 67', experience: 12,
    videoId: 'g0zm39GgRs4',
    bio: {
      az: '12 illik təcrübəsi olan motor mütəxəssisi. BMW, Mercedes və Audi motorlarında dərin biliyə sahibdir. Müştəri məmnuniyyəti onun əsas prioritetidir.',
      ru: 'Специалист по двигателям с 12-летним опытом. Глубокие знания в области двигателей BMW, Mercedes и Audi. Удовлетворённость клиентов — его главный приоритет.',
      en: 'Engine specialist with 12 years of experience. Deep knowledge of BMW, Mercedes and Audi engines. Customer satisfaction is his top priority.',
    },
  },
  {
    id: 2,
    name: 'Vüsal Hüseynov', nameRu: 'Вюсал Гусейнов', nameEn: 'Vusal Huseynov',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80',
    categories: { az: ['Elektrik İşləri', 'Kondisioner'], ru: ['Электрика', 'Кондиционер'], en: ['Electrical', 'AC Repair'] },
    address: { az: 'Binəqədi r., Bakı', ru: 'Бинагади р-н, Баку', en: 'Binagadi dist., Baku' },
    rating: 4.8, reviews: 89, isOpen: true, phone: '+994 55 234 56 78', experience: 8,
    videoId: 'AXi2o7rcphc',
    bio: {
      az: 'Avtomobil elektrikası üzrə 8 illik peşəkar. Kondisioner sistemləri, ECU proqramlaşdırma və elektrik diaqnostikasında ixtisaslaşıb.',
      ru: '8-летний профессионал в области автомобильной электрики. Специализируется на системах кондиционирования, программировании ECU и электрической диагностике.',
      en: '8-year professional in automotive electrical work. Specializes in AC systems, ECU programming and electrical diagnostics.',
    },
  },
  {
    id: 3,
    name: 'Elnur Məmmədov', nameRu: 'Эльнур Мамедов', nameEn: 'Elnur Mammadov',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
    categories: { az: ['Kuzov Təmiri', 'Rəngkarlıq'], ru: ['Кузовной ремонт', 'Покраска'], en: ['Body Repair', 'Painting'] },
    address: { az: 'Sabunçu r., Bakı', ru: 'Сабунчи р-н, Баку', en: 'Sabunchu dist., Baku' },
    rating: 4.7, reviews: 64, isOpen: false, phone: '+994 70 345 67 89', experience: 15,
    bio: {
      az: '15 illik kuzov ustası. Hər növ zədənin aradan qaldırılması, rəngkarlıq və lak örtüyü bərpasında mütəxəssisdir. Nəticələrinə zəmanət verir.',
      ru: '15-летний мастер кузовного ремонта. Специализируется на устранении любых повреждений, покраске и восстановлении лакового покрытия. Гарантирует результаты.',
      en: '15-year body repair master. Specializes in all types of damage repair, painting and lacquer restoration. Guarantees results.',
    },
  },
  {
    id: 4,
    name: 'Tural Qasımov', nameRu: 'Турал Касимов', nameEn: 'Tural Gasimov',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80',
    categories: { az: ['Təkər Dəyişimi', 'Balanslaşdırma'], ru: ['Шиномонтаж', 'Балансировка'], en: ['Tire Change', 'Balancing'] },
    address: { az: 'Xətai r., Bakı', ru: 'Хатаи р-н, Баку', en: 'Khatai dist., Baku' },
    rating: 4.9, reviews: 203, isOpen: true, phone: '+994 51 456 78 90', experience: 10,
    videoId: 'hBPvKna1Adw',
    bio: {
      az: 'Bakının ən sürətli şin ustası. 10 dəqiqəyə tam şin dəyişimi. Bütün ölçü və markalar üçün balanslaşdırma xidməti göstərir.',
      ru: 'Самый быстрый шинный мастер в Баку. Полная замена шин за 10 минут. Услуги балансировки для всех размеров и марок.',
      en: "Baku's fastest tire specialist. Full tire change in 10 minutes. Balancing service for all sizes and brands.",
    },
  },
  {
    id: 5,
    name: 'Nicat Babayev', nameRu: 'Ниджат Бабаев', nameEn: 'Nijat Babayev',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=80',
    categories: { az: ['Yağ Dəyişimi', 'Texniki Xidmət'], ru: ['Замена масла', 'ТО'], en: ['Oil Change', 'Maintenance'] },
    address: { az: 'Suraxanı r., Bakı', ru: 'Сурахани р-н, Баку', en: 'Surakhani dist., Baku' },
    rating: 4.6, reviews: 51, isOpen: true, phone: '+994 77 567 89 01', experience: 6,
    bio: {
      az: 'Profilaktik texniki xidmət üzrə mütəxəssis. Yağ, filtr, əyləc mayesi dəyişimi və tam TO xidmətləri göstərir. Sərfəli qiymətlər.',
      ru: 'Специалист по профилактическому техническому обслуживанию. Предоставляет услуги замены масла, фильтра, тормозной жидкости и полного ТО. Доступные цены.',
      en: 'Preventive maintenance specialist. Provides oil, filter, brake fluid change and full service maintenance. Affordable prices.',
    },
  },
  {
    id: 6,
    name: 'Kamran Rzayev', nameRu: 'Камран Рзаев', nameEn: 'Kamran Rzayev',
    image: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&q=80',
    categories: { az: ['Süspansiyon', 'Əyləc Sistemi'], ru: ['Подвеска', 'Тормозная система'], en: ['Suspension', 'Brake System'] },
    address: { az: 'Yasamal r., Bakı', ru: 'Ясамал р-н, Баку', en: 'Yasamal dist., Baku' },
    rating: 4.8, reviews: 88, isOpen: false, phone: '+994 50 678 90 12', experience: 11,
    videoId: 'SbNwS1qXj1Q',
    bio: {
      az: 'Süspansiyon və əyləc sistemləri üzrə 11 illik peşəkar. Xüsusilə yük avtomobilləri və idman avtomobilləri üçün ixtisaslaşıb.',
      ru: '11-летний профессионал по подвеске и тормозным системам. Специализируется на грузовых автомобилях и спортивных машинах.',
      en: '11-year professional in suspension and brake systems. Specializes in trucks and sports cars.',
    },
  },
]

export const autoservices = [
  {
    id: 1, name: 'AutoPro Servis',
    image: 'https://images.unsplash.com/photo-1615906655593-ad0386982a0f?w=600&q=80',
    categories: { az: ['Tam Xidmət', 'Diaqnostika', 'Motor'], ru: ['Полный сервис', 'Диагностика', 'Двигатель'], en: ['Full Service', 'Diagnostics', 'Engine'] },
    address: { az: 'Neftçilər pr. 45, Bakı', ru: 'пр. Нефтяников 45, Баку', en: '45 Neftchilar Ave., Baku' },
    rating: 4.9, reviews: 312, isOpen: true, phone: '+994 12 345 67 89',
    image2: 'https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?w=600&q=80',
    videoId: 'uNPDtUxshGk',
    description: {
      az: 'Bakının ən tam avtoservis mərkəzi. 2012-ci ildən fəaliyyət göstərir. 20 ixtisaslı texnik, müasir diaqnostika avadanlığı, rəsmi zəmanət.',
      ru: 'Самый полный центр автосервиса в Баку. Работает с 2012 года. 20 квалифицированных техников, современное диагностическое оборудование, официальная гарантия.',
      en: "Baku's most comprehensive auto service center. Operating since 2012. 20 qualified technicians, modern diagnostic equipment, official warranty.",
    },
  },
  {
    id: 2, name: 'SpeedFix Center',
    image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=600&q=80',
    categories: { az: ['Sürətli Xidmət', 'Yağ', 'Filtr'], ru: ['Быстрый сервис', 'Масло', 'Фильтр'], en: ['Quick Service', 'Oil', 'Filter'] },
    address: { az: 'İstiqlaliyyət k. 12, Bakı', ru: 'ул. Истиглалиет 12, Баку', en: '12 Istiglaliyyat St., Baku' },
    rating: 4.7, reviews: 198, isOpen: true, phone: '+994 12 456 78 90',
    description: {
      az: 'Sürət bizim prioritetimizdir. 30 dəqiqə ərzində yağ dəyişimi, filtr dəyişimi və standart TO xidmətləri. Görüş lazım deyil.',
      ru: 'Скорость — наш приоритет. Замена масла, фильтра и стандартное ТО за 30 минут. Запись не требуется.',
      en: 'Speed is our priority. Oil change, filter replacement and standard maintenance in 30 minutes. No appointment needed.',
    },
  },
  {
    id: 3, name: 'TechCar Workshop',
    image: 'https://images.unsplash.com/photo-1619642737579-a7474bee1044?w=600&q=80',
    categories: { az: ['Elektron Sistemlər', 'Diaqnostika'], ru: ['Электронные системы', 'Диагностика'], en: ['Electronic Systems', 'Diagnostics'] },
    address: { az: 'Hüsü Hacıyev k. 7, Bakı', ru: 'ул. Гусу Гаджиева 7, Баку', en: '7 Husu Hajiyev St., Baku' },
    rating: 4.8, reviews: 145, isOpen: false, phone: '+994 12 567 89 01',
    videoId: 'TbFYIuAIQrw',
    description: {
      az: 'Müasir elektron diaqnostika mərkəzi. OBD, ABS, airbag, ECU kalibrasiya xidmətləri. Bütün Avropa markaları üçün.',
      ru: 'Современный центр электронной диагностики. Услуги OBD, ABS, airbag, калибровки ECU. Для всех европейских марок.',
      en: 'Modern electronic diagnostics center. OBD, ABS, airbag, ECU calibration services. For all European brands.',
    },
  },
  {
    id: 4, name: 'EuroAuto Servis',
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&q=80',
    categories: { az: ['Avropa Avtomobilləri', 'BMW', 'Mercedes'], ru: ['Европейские авто', 'BMW', 'Mercedes'], en: ['European Cars', 'BMW', 'Mercedes'] },
    address: { az: 'Üzeyir Hacıbəyov k. 23, Bakı', ru: 'ул. Уз. Гаджибекова 23, Баку', en: '23 Uzeyir Hajibekov St., Baku' },
    rating: 4.9, reviews: 267, isOpen: true, phone: '+994 12 678 90 12',
    videoId: 'SbNwS1qXj1Q',
    description: {
      az: 'BMW, Mercedes, Audi, Volkswagen üzrə ixtisaslaşmış servis. Orijinal ehtiyat hissələri ilə işləyirik. Rəsmi dealer standartlarına uyğun xidmət.',
      ru: 'Специализированный сервис по BMW, Mercedes, Audi, Volkswagen. Работаем с оригинальными запчастями. Сервис по стандартам официального дилера.',
      en: 'Specialized service for BMW, Mercedes, Audi, Volkswagen. We work with original spare parts. Service to official dealer standards.',
    },
  },
  {
    id: 5, name: 'Azərbaycan AutoCare',
    image: 'https://images.unsplash.com/photo-1507136566006-cfc505b114fc?w=600&q=80',
    categories: { az: ['Kuzov', 'Rəngkarlıq', 'Pasta'], ru: ['Кузов', 'Покраска', 'Полировка'], en: ['Body', 'Painting', 'Polishing'] },
    address: { az: 'Rəşid Behbudov k. 5, Bakı', ru: 'ул. Р. Бехбудова 5, Баку', en: '5 R. Behbudov St., Baku' },
    rating: 4.6, reviews: 89, isOpen: true, phone: '+994 12 789 01 23',
    description: {
      az: 'Kuzov, rəngkarlıq və polirovka üzrə ixtisaslaşmış mərkəz. Rəng uyğunlaşdırma texnologiyası, zərərə görə sığorta işləri.',
      ru: 'Специализированный центр кузовного ремонта, покраски и полировки. Технология подбора цвета, страховые работы по ущербу.',
      en: 'Specialized center for body repair, painting and polishing. Color matching technology, insurance damage work.',
    },
  },
  {
    id: 6, name: 'JapanTech Motors',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    categories: { az: ['Yapon Avtomobilləri', 'Toyota', 'Honda'], ru: ['Японские авто', 'Toyota', 'Honda'], en: ['Japanese Cars', 'Toyota', 'Honda'] },
    address: { az: 'Nehrəm k. 18, Bakı', ru: 'ул. Нехрем 18, Баку', en: '18 Nehram St., Baku' },
    rating: 4.7, reviews: 134, isOpen: false, phone: '+994 12 890 12 34',
    videoId: 'g0zm39GgRs4',
    description: {
      az: 'Toyota, Honda, Nissan, Mazda üzrə Bakının lider servis mərkəzi. Yapon texnikasının incəliklərini bilirik. 15 illik təcrübə.',
      ru: 'Ведущий сервисный центр Баку по Toyota, Honda, Nissan, Mazda. Знаем тонкости японской техники. 15 лет опыта.',
      en: "Baku's leading service center for Toyota, Honda, Nissan, Mazda. We know the nuances of Japanese technology. 15 years experience.",
    },
  },
]

export const serviceCategories = [
  { id: 1, icon: 'Wrench',      color: 'from-blue-500 to-blue-600',    name: { az: 'Motor Təmiri',   ru: 'Ремонт двигателя', en: 'Engine Repair' },          count: 48 },
  { id: 2, icon: 'Zap',         color: 'from-yellow-500 to-orange-500',name: { az: 'Elektrik İşləri',ru: 'Электрика',         en: 'Electrical Work' },         count: 35 },
  { id: 3, icon: 'Car',         color: 'from-green-500 to-emerald-500',name: { az: 'Kuzov Təmiri',   ru: 'Кузовной ремонт',  en: 'Body Repair' },             count: 27 },
  { id: 4, icon: 'Disc',        color: 'from-purple-500 to-purple-600',name: { az: 'Təkər Xidməti',  ru: 'Шиномонтаж',       en: 'Tire Service' },            count: 62 },
  { id: 5, icon: 'Wind',        color: 'from-red-500 to-rose-500',     name: { az: 'Kondisioner',    ru: 'Кондиционер',      en: 'AC Service' },              count: 41 },
  { id: 6, icon: 'ClipboardList',color: 'from-indigo-500 to-indigo-600',name: { az: 'Texniki Baxış', ru: 'Техосмотр',        en: 'Technical Inspection' },    count: 55 },
  { id: 7, icon: 'Droplets',    color: 'from-cyan-500 to-blue-500',    name: { az: 'Yağ Dəyişimi',   ru: 'Замена масла',     en: 'Oil Change' },              count: 78 },
  { id: 8, icon: 'Shield',      color: 'from-slate-500 to-slate-600',  name: { az: 'Əyləc Sistemi',  ru: 'Тормоза',          en: 'Brake System' },            count: 33 },
]

export const shops = [
  {
    id: 1,
    name: 'AutoParts AZ',
    image: 'https://images.unsplash.com/photo-1517524206127-48bbd363f3d7?w=600&q=80',
    categories: { az: ['Orijinal Hissələr', 'BMW', 'Mercedes'], ru: ['Оригинальные запчасти', 'BMW', 'Mercedes'], en: ['Original Parts', 'BMW', 'Mercedes'] },
    address: { az: 'Həsən Əliyev k. 34, Bakı', ru: 'ул. Г. Алиева 34, Баку', en: '34 Hasan Aliyev St., Baku' },
    rating: 4.8,
    reviews: 156,
    isOpen: true,
    phone: '+994 12 111 22 33',
  },
  {
    id: 2,
    name: 'SpeedParts Store',
    image: 'https://images.unsplash.com/photo-1504222490345-c075b7b4f8d4?w=600&q=80',
    categories: { az: ['Aftermarket', 'Aksesuarlar'], ru: ['Aftermarket', 'Аксессуары'], en: ['Aftermarket', 'Accessories'] },
    address: { az: 'Əliağa Vahid k. 9, Bakı', ru: 'ул. Алиага Вахид 9, Баку', en: '9 Aliaga Vahid St., Baku' },
    rating: 4.6,
    reviews: 98,
    isOpen: true,
    phone: '+994 12 222 33 44',
  },
  {
    id: 3,
    name: 'MotoShop Baku',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=600&q=80',
    categories: { az: ['Yağlar', 'Süzgəclər', 'Akkumulyator'], ru: ['Масла', 'Фильтры', 'Аккумуляторы'], en: ['Oils', 'Filters', 'Batteries'] },
    address: { az: 'Şəmsi Bədəlbəyli k. 3, Bakı', ru: 'ул. Ш. Бадалбейли 3, Баку', en: '3 Shamsi Badalbeyli St., Baku' },
    rating: 4.7,
    reviews: 112,
    isOpen: false,
    phone: '+994 12 333 44 55',
  },
  {
    id: 4,
    name: 'TurboZone',
    image: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80',
    categories: { az: ['Tuning', 'Sport Aksesuarlar'], ru: ['Тюнинг', 'Спорт аксессуары'], en: ['Tuning', 'Sport Accessories'] },
    address: { az: 'Mikayıl Müşfiq k. 15, Bakı', ru: 'ул. Микаил Мушфик 15, Баку', en: '15 Mikayil Mushfiq St., Baku' },
    rating: 4.9,
    reviews: 74,
    isOpen: true,
    phone: '+994 12 444 55 66',
  },
]

export const blogPosts = [
  {
    id: 1,
    title: { az: 'Yay mövsümündə avtomobilinizi necə hazırlayarsınız?', ru: 'Как подготовить автомобиль к лету?', en: 'How to prepare your car for summer?' },
    excerpt: { az: 'Yay istisindən avtomobilinizi qorumaq üçün 10 vacib addım...', ru: '10 важных шагов для защиты вашего автомобиля от летней жары...', en: '10 important steps to protect your car from summer heat...' },
    image: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&q=80',
    category: { az: 'Məsləhətlər', ru: 'Советы', en: 'Tips' },
    date: '2026-03-01',
    readTime: 5,
    author: 'Avtomobil Eksperti',
    videoId: 'g0zm39GgRs4',
    content: {
      az: [
        { type: 'paragraph', text: 'Yay mövsümü avtomobil sahibləri üçün həm imkan, həm də çətinlik dövrüdür. Bakının yay aylarında temperatur 40°C-yə çatır və bu, avtomobilinizin bir çox hissəsinə ciddi təsir göstərə bilər.' },
        { type: 'heading', text: '1. Soyutma sistemini yoxlayın' },
        { type: 'paragraph', text: 'İstilik mövsümündə ən vacib sistem soyutma sistemidir. Antifrizi vaxtında dəyişin, radiator şlanqlarını yoxlayın. Aşırı qızma motora dönməz zərər vura bilər.' },
        { type: 'tip', text: 'Antifriz səviyyəsini hər 2 haftada bir yoxlayın. Səviyyə MIN xəttindən aşağıdırsa dərhal doldurun.' },
        { type: 'heading', text: '2. Kondisioner sistemi' },
        { type: 'paragraph', text: 'Kondisionerin soyutma gücü azalıbsa, freon doldurmaq lazım ola bilər. Bakı-nin yay istisindəkondisioner olmadan sürüş həm narahat, həm də təhlükəlidir.' },
        { type: 'heading', text: '3. Şin təzyiqini tənzimləyin' },
        { type: 'paragraph', text: 'İsti havada asfalt qızmış olduğundan şin təzyiqi artır. Səhər saatlarında, avtomobil soyuq halda şin təzyiqini yoxlayın. Tövsiyə edilən təzyiq avtomobilin qapısında yazılıb.' },
        { type: 'tip', text: 'Yay üçün şin təzyiqini 0.1-0.2 bar aşağı tutmaq tövsiyə olunur.' },
        { type: 'heading', text: '4. Akümülyator vəziyyəti' },
        { type: 'paragraph', text: 'Həm həddən artıq isti, həm də soyuq akümülyatoru zədələyir. Yayda kondisioner və digər elektrik cihazlarının yükü altında akümülyator daha tez tükənir. Şarj səviyyəsini yoxladın.' },
        { type: 'heading', text: '5. Avtomobilinizin rəngini qoruyun' },
        { type: 'paragraph', text: 'UV şüaları boyaya ciddi zərər verir. Yay mövsümündən əvvəl avtomobilinizi silin və mum tətbiq edin. Mümkünsə kölgəli yerdə park edin.' },
      ],
      ru: [
        { type: 'paragraph', text: 'Летний сезон — это время возможностей и испытаний для владельцев автомобилей. В летние месяцы в Баку температура достигает 40°C, что может серьёзно повлиять на многие части вашего автомобиля.' },
        { type: 'heading', text: '1. Проверьте систему охлаждения' },
        { type: 'paragraph', text: 'В жаркое время года система охлаждения является наиболее важной. Своевременно меняйте антифриз, проверяйте шланги радиатора. Перегрев может нанести необратимый ущерб двигателю.' },
        { type: 'tip', text: 'Проверяйте уровень антифриза каждые 2 недели. Если уровень ниже отметки MIN — немедленно долейте.' },
        { type: 'heading', text: '2. Система кондиционирования' },
        { type: 'paragraph', text: 'Если охлаждающая способность кондиционера снизилась, возможно, потребуется дозаправка фреоном. Езда без кондиционера в летнюю жару Баку неудобна и опасна.' },
        { type: 'heading', text: '3. Отрегулируйте давление в шинах' },
        { type: 'paragraph', text: 'В жаркую погоду, когда асфальт нагрет, давление в шинах возрастает. Проверяйте давление утром, когда автомобиль холодный. Рекомендуемое давление указано на двери автомобиля.' },
        { type: 'heading', text: '4. Состояние аккумулятора' },
        { type: 'paragraph', text: 'Как сильная жара, так и сильный холод повреждают аккумулятор. Летом под нагрузкой кондиционера и других электроприборов аккумулятор разряжается быстрее. Проверьте уровень заряда.' },
        { type: 'heading', text: '5. Защитите краску автомобиля' },
        { type: 'paragraph', text: 'УФ-лучи серьёзно повреждают краску. Перед летним сезоном отполируйте автомобиль и нанесите воск. По возможности паркуйтесь в тени.' },
      ],
      en: [
        { type: 'paragraph', text: "Summer season is both an opportunity and a challenge for car owners. During Baku's summer months, temperatures reach 40°C, which can seriously affect many parts of your vehicle." },
        { type: 'heading', text: '1. Check the cooling system' },
        { type: 'paragraph', text: 'The cooling system is most critical during hot season. Change antifreeze on time, check radiator hoses. Overheating can cause irreversible damage to the engine.' },
        { type: 'tip', text: 'Check antifreeze level every 2 weeks. If the level is below MIN mark — refill immediately.' },
        { type: 'heading', text: '2. Air conditioning system' },
        { type: 'paragraph', text: "If your AC's cooling power has decreased, you may need a freon refill. Driving without AC in Baku's summer heat is both uncomfortable and dangerous." },
        { type: 'heading', text: '3. Adjust tire pressure' },
        { type: 'paragraph', text: "In hot weather, tire pressure increases as asphalt heats up. Check tire pressure in the morning when the car is cold. Recommended pressure is written on the car's door." },
        { type: 'heading', text: '4. Battery condition' },
        { type: 'paragraph', text: 'Both extreme heat and cold damage the battery. In summer, the battery drains faster under the load of the AC and other electrical devices. Check the charge level.' },
        { type: 'heading', text: '5. Protect your car paint' },
        { type: 'paragraph', text: 'UV rays seriously damage paint. Before summer season, polish your car and apply wax. Park in the shade when possible.' },
      ],
    },
  },
  {
    id: 2,
    title: { az: 'Motor yağını nə vaxt dəyişmək lazımdır?', ru: 'Когда нужно менять моторное масло?', en: 'When should you change engine oil?' },
    excerpt: { az: 'Motor yağının dəyişim vaxtını müəyyən etmək üçün bilməli olduğunuz hər şey...', ru: 'Всё, что нужно знать для определения времени замены масла...', en: 'Everything you need to know to determine when to change oil...' },
    image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&q=80',
    category: { az: 'Texniki', ru: 'Технические', en: 'Technical' },
    date: '2026-02-20',
    readTime: 4,
    author: 'Texniki Komanda',
    videoId: 'AXi2o7rcphc',
    content: {
      az: [
        { type: 'paragraph', text: 'Motor yağı avtomobilin ürəyidir. Düzgün intervalda dəyişilməyən yağ motorun ömrünü əhəmiyyətli dərəcədə qısaldır.' },
        { type: 'heading', text: 'Klassik qayda: 5.000-10.000 km' },
        { type: 'paragraph', text: 'Əksər avtomobillər üçün yağ dəyişimi 5.000-10.000 km aralığında tövsiyə olunur. Lakin bu rəqəm istifadə olunan yağın növündən asılıdır.' },
        { type: 'tip', text: 'Sintetik yağlar 10.000-15.000 km xidmət göstərə bilər. Mineral yağlar isə daha tez — 5.000 km-dən sonra dəyişdirilməlidir.' },
        { type: 'heading', text: 'Şəhər trafikinin təsiri' },
        { type: 'paragraph', text: 'Bakı tıxaclarında sürüş yağı daha tez köhnəldir. Qısaməsafəli dayanıb-getmə rejimi, yüksək temperatur — bunlar yağı daha sürətlə deqradasiyaya uğradır.' },
        { type: 'heading', text: 'Yağın dəyişilməsi vaxtı gəldiyini necə anlayarsınız?' },
        { type: 'paragraph', text: 'Yağ rəngi qara-qəhvəyi olubsa, dipstikdə yağ lüzumsuz qatılıq göstərirsə, motor səs-küy çıxarırsа — bunlar dəyişim vaxtının gəldiyini bildirən əlamətlərdir.' },
      ],
      ru: [
        { type: 'paragraph', text: 'Моторное масло — это сердце автомобиля. Масло, не заменённое в правильные интервалы, значительно сокращает срок службы двигателя.' },
        { type: 'heading', text: 'Классическое правило: 5 000–10 000 км' },
        { type: 'paragraph', text: 'Для большинства автомобилей замена масла рекомендуется в диапазоне 5 000–10 000 км. Однако эта цифра зависит от типа используемого масла.' },
        { type: 'tip', text: 'Синтетические масла могут прослужить 10 000–15 000 км. Минеральные масла следует менять быстрее — после 5 000 км.' },
        { type: 'heading', text: 'Влияние городского трафика' },
        { type: 'paragraph', text: 'Езда в пробках Баку ускоряет износ масла. Режим частых остановок и движения на короткие дистанции, высокая температура — всё это ускоряет деградацию масла.' },
        { type: 'heading', text: 'Как понять, что пора менять масло?' },
        { type: 'paragraph', text: 'Если цвет масла стал чёрно-коричневым, щуп показывает излишнюю вязкость, двигатель шумит — это признаки того, что пришло время замены.' },
      ],
      en: [
        { type: 'paragraph', text: "Engine oil is the heart of your car. Oil that isn't changed at proper intervals significantly shortens engine life." },
        { type: 'heading', text: 'Classic rule: 5,000-10,000 km' },
        { type: 'paragraph', text: 'For most cars, oil change is recommended every 5,000-10,000 km. However, this number depends on the type of oil used.' },
        { type: 'tip', text: 'Synthetic oils can last 10,000-15,000 km. Mineral oils should be changed sooner — after 5,000 km.' },
        { type: 'heading', text: 'Effect of city traffic' },
        { type: 'paragraph', text: "Driving in Baku's traffic ages oil faster. Short stop-and-go trips, high temperature — these accelerate oil degradation." },
        { type: 'heading', text: 'How to know when to change oil?' },
        { type: 'paragraph', text: "If oil color is dark brown-black, dipstick shows excessive thickness, engine is noisy — these are signs it's time to change." },
      ],
    },
  },
  {
    id: 3,
    title: { az: 'Elektrik avtomobilləri: Bakıda nə dəyişdi?', ru: 'Электромобили: что изменилось в Баку?', en: 'Electric cars: What changed in Baku?' },
    excerpt: { az: 'Elektrik avtomobillərinin Azərbaycandakı vəziyyəti və gələcəyi...', ru: 'Текущее положение и будущее электромобилей в Азербайджане...', en: 'Current state and future of electric cars in Azerbaijan...' },
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600&q=80',
    category: { az: 'Trend', ru: 'Тренды', en: 'Trends' },
    date: '2026-02-10',
    readTime: 6,
    author: 'Redaksiya',
    videoId: 'WOW5AupXi7c',
    content: {
      az: [
        { type: 'paragraph', text: 'Azərbaycanda elektrik avtomobillərinin sayı son 2 ildə 3 dəfə artıb. Bakının küçələrində artıq Tesla, BYD, Hyundai Ioniq kimi markaları tez-tez görmək mümkündür.' },
        { type: 'heading', text: 'Şarj infrastrukturu' },
        { type: 'paragraph', text: 'Bakıda şarj stansiyalarının sayı 2025-ci ildə 200-ü keçdi. Əsas ticarət mərkəzlərinin, otellərin, bəzi mağazaların yanında artıq şarj nöqtələri mövcuddur.' },
        { type: 'tip', text: 'Bakıda PlugShare tətbiqi ilə ən yaxın şarj stansiyasını tapa bilərsiniz.' },
        { type: 'heading', text: 'Gömrük güzəştləri' },
        { type: 'paragraph', text: 'Azərbaycan hökuməti elektrik avtomobilləri üçün gömrük güzəştlərini uzatdı. Bu, qiymətlərin əhəmiyyətli dərəcədə aşağı düşməsinə səbəb oldu.' },
        { type: 'heading', text: 'Gələcəyə baxış' },
        { type: 'paragraph', text: '2030-cu ilə qədər Azərbaycanda satılan avtomobillərin 20%-nin elektrik olacağı proqnozlaşdırılır. Bu hədəfə çatmaq üçün infrastruktur investisiyaları davam edir.' },
      ],
      ru: [
        { type: 'paragraph', text: 'За последние 2 года количество электромобилей в Азербайджане выросло в 3 раза. На улицах Баку теперь всё чаще можно увидеть Tesla, BYD, Hyundai Ioniq и другие марки.' },
        { type: 'heading', text: 'Зарядная инфраструктура' },
        { type: 'paragraph', text: 'В 2025 году количество зарядных станций в Баку превысило 200. Зарядные точки уже доступны у основных торговых центров, отелей и некоторых магазинов.' },
        { type: 'tip', text: 'В Баку вы можете найти ближайшую зарядную станцию с помощью приложения PlugShare.' },
        { type: 'heading', text: 'Таможенные льготы' },
        { type: 'paragraph', text: 'Правительство Азербайджана продлило таможенные льготы на электромобили. Это привело к значительному снижению цен.' },
        { type: 'heading', text: 'Взгляд в будущее' },
        { type: 'paragraph', text: 'По прогнозам, к 2030 году 20% продаваемых в Азербайджане автомобилей будут электрическими. Для достижения этой цели продолжаются инвестиции в инфраструктуру.' },
      ],
      en: [
        { type: 'paragraph', text: "The number of electric vehicles in Azerbaijan has tripled in the last 2 years. Tesla, BYD, Hyundai Ioniq and similar brands are now frequently spotted on Baku's streets." },
        { type: 'heading', text: 'Charging infrastructure' },
        { type: 'paragraph', text: "The number of charging stations in Baku exceeded 200 in 2025. Charging points are now available at major shopping centers, hotels, and some stores." },
        { type: 'tip', text: 'You can find the nearest charging station in Baku using the PlugShare app.' },
        { type: 'heading', text: 'Customs incentives' },
        { type: 'paragraph', text: 'The Azerbaijani government extended customs incentives for electric vehicles. This led to a significant drop in prices.' },
        { type: 'heading', text: 'Looking ahead' },
        { type: 'paragraph', text: 'It is forecast that by 2030, 20% of vehicles sold in Azerbaijan will be electric. Infrastructure investments continue to meet this target.' },
      ],
    },
  },
  {
    id: 4,
    title: { az: 'Qışda sürüşlü yollarda etməli olduğunuz 7 şey', ru: '7 вещей, которые нужно делать на скользких зимних дорогах', en: '7 things to do on slippery winter roads' },
    excerpt: { az: 'Qışın ən çətin anlarında avtomobil idarəetməsinin sirləri...', ru: 'Секреты вождения автомобиля в самые трудные зимние моменты...', en: 'Secrets of car control in the most difficult winter moments...' },
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
    category: { az: 'Təhlükəsizlik', ru: 'Безопасность', en: 'Safety' },
    date: '2026-01-28',
    readTime: 3,
    author: 'Sürüş Eksperti',
    videoId: 'hBPvKna1Adw',
    content: {
      az: [
        { type: 'paragraph', text: 'Qış aylarında Bakıda buz tutmuş yollar nadir deyil. Bu 7 tövsiyə sizi ciddi qəzalardan qoruyacaq.' },
        { type: 'heading', text: '1. Sürəti azaldın' },
        { type: 'paragraph', text: 'Sürüşlü yolda dayanan məsafə normal şəraitə nisbətən 3-4 dəfə uzanır. Sürəti 30-40% azaltmaq ən sadə, amma ən effektiv tədbirdir.' },
        { type: 'tip', text: 'Buz üzərində ABS sistemi belə sizi tam qorumur. Ən yaxşı müdafiə — aşağı sürət.' },
        { type: 'heading', text: '2. Ani manevərlərdən çəkinin' },
        { type: 'paragraph', text: 'Sürüşlü yolda kəskin döndürmə, ani əyləc — bunlar avtomobili nəzarətsiz vəziyyətə sala bilər. Hər hərəkəti yavaş və müntəzəm edin.' },
        { type: 'heading', text: '3. Qış şinlərindən istifadə edin' },
        { type: 'paragraph', text: 'Qış şinləri yalnız qar üçün deyil. 7°C-dən aşağı temperaturda yay şinləri sərtləşir və tutma keyfiyyəti kəskin düşür.' },
        { type: 'heading', text: '4. Məsafəni artırın' },
        { type: 'paragraph', text: 'Öndəki avtomobillə arası iki dəfə artırın. Tıxacda belə.' },
        { type: 'heading', text: '5. Əyləci düzgün istifadə edin' },
        { type: 'paragraph', text: 'ABS sistemi olan avtomobillərdə əyləci bərk basın — sistem öz işini görəcək. ABS olmayan avtomobillərdə isə əyləci aralıq-aralıq basın.' },
        { type: 'heading', text: '6. Farları yandırın' },
        { type: 'paragraph', text: 'Günortadan sonra da gün işığı yorucu olsa da, farlarınızı yandırmaq sizin görünürlüyünüzü artırır.' },
        { type: 'heading', text: '7. Sakit olun' },
        { type: 'paragraph', text: 'Sürüşməyə başladıqda panikaya qapılmayın. Sükanı sürüşmə istiqamətinə çevirin, qaz pedalını azaldın.' },
      ],
      ru: [
        { type: 'paragraph', text: 'Обледенелые дороги в Баку зимой не редкость. Эти 7 советов защитят вас от серьёзных аварий.' },
        { type: 'heading', text: '1. Снизьте скорость' },
        { type: 'paragraph', text: 'На скользкой дороге тормозной путь увеличивается в 3–4 раза по сравнению с обычными условиями. Снижение скорости на 30–40% — самая простая и эффективная мера.' },
        { type: 'tip', text: 'На льду даже система ABS не защитит вас полностью. Лучшая защита — низкая скорость.' },
        { type: 'heading', text: '2. Избегайте резких манёвров' },
        { type: 'paragraph', text: 'Резкий поворот руля, резкое торможение на скользкой дороге могут привести к потере управления. Выполняйте каждое движение медленно и равномерно.' },
        { type: 'heading', text: '3. Используйте зимние шины' },
        { type: 'paragraph', text: 'Зимние шины нужны не только для снега. При температуре ниже 7°C летние шины твердеют и резко теряют сцепление.' },
        { type: 'heading', text: '4. Увеличьте дистанцию' },
        { type: 'paragraph', text: 'Увеличьте дистанцию до впереди идущего автомобиля вдвое. Даже в пробке.' },
        { type: 'heading', text: '5. Правильно пользуйтесь тормозами' },
        { type: 'paragraph', text: 'На автомобилях с ABS нажимайте на тормоз сильно — система сделает своё дело. На автомобилях без ABS тормозите прерывисто.' },
        { type: 'heading', text: '6. Включайте фары' },
        { type: 'paragraph', text: 'Даже если дневной свет кажется достаточным, включённые фары повышают вашу заметность.' },
        { type: 'heading', text: '7. Сохраняйте спокойствие' },
        { type: 'paragraph', text: 'Если начали скользить — не паникуйте. Поверните руль в направлении заноса, уберите ногу с газа.' },
      ],
      en: [
        { type: 'paragraph', text: "Icy roads in Baku during winter aren't uncommon. These 7 tips will protect you from serious accidents." },
        { type: 'heading', text: '1. Reduce speed' },
        { type: 'paragraph', text: 'On slippery roads, stopping distance is 3-4 times longer than normal. Reducing speed by 30-40% is the simplest but most effective measure.' },
        { type: 'tip', text: 'On ice, even ABS cannot fully protect you. The best protection is low speed.' },
        { type: 'heading', text: '2. Avoid sudden maneuvers' },
        { type: 'paragraph', text: 'Sharp turns, sudden braking on slippery roads can cause loss of control. Make every movement slow and gradual.' },
        { type: 'heading', text: '3. Use winter tires' },
        { type: 'paragraph', text: 'Winter tires are not just for snow. Below 7°C, summer tires harden and grip drops sharply.' },
        { type: 'heading', text: '4. Increase distance' },
        { type: 'paragraph', text: 'Double the gap to the car ahead. Even in traffic.' },
        { type: 'heading', text: '5. Use brakes correctly' },
        { type: 'paragraph', text: 'On cars with ABS, press the brake hard — the system will do its job. On cars without ABS, apply brakes in pulses.' },
        { type: 'heading', text: '6. Turn on lights' },
        { type: 'paragraph', text: 'Even if daylight seems sufficient, turning on your lights increases your visibility.' },
        { type: 'heading', text: '7. Stay calm' },
        { type: 'paragraph', text: "If you start sliding — don't panic. Turn the wheel in the direction of the slide, ease off the gas." },
      ],
    },
  },
  {
    id: 5,
    title: { az: 'Avtomobilinizi satmazdan əvvəl bilməli olduğunuz hər şey', ru: 'Всё, что нужно знать перед продажей автомобиля', en: 'Everything you need to know before selling your car' },
    excerpt: { az: 'Avtomobilinizi ən yaxşı qiymətə satmaq üçün peşəkar məsləhətlər...', ru: 'Профессиональные советы по продаже автомобиля по лучшей цене...', en: 'Professional tips for selling your car at the best price...' },
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80',
    category: { az: 'Məsləhətlər', ru: 'Советы', en: 'Tips' },
    date: '2026-01-15',
    readTime: 7,
    author: 'Avtomobil Eksperti',
    videoId: 'SbNwS1qXj1Q',
    content: {
      az: [
        { type: 'paragraph', text: 'Avtomobilinizi satmaq istəyirsiniz? Bu proses düzgün hazırlıq olmadan sinir bozucu ola bilər. Bu məqalə sizə maksimum qiymət əldə etməyə kömək edəcək.' },
        { type: 'heading', text: 'Satışdan əvvəl texniki yoxlama' },
        { type: 'paragraph', text: 'Alıcılar texniki sazlıq sertifikatına böyük əhəmiyyət verirlər. Satışdan əvvəl avtomobilinizi texniki baxışdan keçirin, aşkar nasazlıqları aradan qaldırın.' },
        { type: 'tip', text: 'Kiçik xərclə aradan qaldırılan nasazlıqlar (məsələn, yanacaq kəpənəyinin dəyişdirilməsi) satış qiymətini 500-1000 AZN artıra bilər.' },
        { type: 'heading', text: 'Vizual hazırlıq' },
        { type: 'paragraph', text: 'İlk təəssürat hər şeydir. Peşəkar dərin təmizlik (karosseriyanın cilalanması, salona dərin yuyulma) almaq-satmaq prosesinə ciddi müsbət təsir göstərir.' },
        { type: 'heading', text: 'Düzgün qiymət qoyun' },
        { type: 'paragraph', text: 'turbo.az, tap.az kimi platformalarda eyni model avtomobillərin qiymətlərini araşdırın. Orta qiymətdən 5-10% aşağı başlamaq tez satış imkanı yaradır.' },
        { type: 'heading', text: 'Sənədləri hazırlayın' },
        { type: 'paragraph', text: 'Texniki pasport, sığorta, texniki baxış sertifikatı — bunların hamısı hazır olmalıdır. Sənəd problemi olan avtomobil satılmaz.' },
      ],
      ru: [
        { type: 'paragraph', text: 'Хотите продать свой автомобиль? Без правильной подготовки этот процесс может стать нервным испытанием. Эта статья поможет вам получить максимальную цену.' },
        { type: 'heading', text: 'Техническая проверка перед продажей' },
        { type: 'paragraph', text: 'Покупатели придают большое значение сертификату технической исправности. Пройдите техосмотр перед продажей, устраните явные неисправности.' },
        { type: 'tip', text: 'Неисправности, устранённые за небольшую плату (например, замена топливного фильтра), могут увеличить цену продажи на 500–1000 AZN.' },
        { type: 'heading', text: 'Визуальная подготовка' },
        { type: 'paragraph', text: 'Первое впечатление — это всё. Профессиональная глубокая чистка (полировка кузова, глубокая мойка салона) серьёзно положительно влияет на процесс купли-продажи.' },
        { type: 'heading', text: 'Установите правильную цену' },
        { type: 'paragraph', text: 'Изучите цены на аналогичные модели на таких платформах, как turbo.az, tap.az. Начать с 5–10% ниже средней цены — значит создать возможность для быстрой продажи.' },
        { type: 'heading', text: 'Подготовьте документы' },
        { type: 'paragraph', text: 'Техпаспорт, страховка, сертификат техосмотра — всё это должно быть готово. Автомобиль с проблемными документами не продаётся.' },
      ],
      en: [
        { type: 'paragraph', text: 'Want to sell your car? Without proper preparation, this process can be nerve-racking. This article will help you get the maximum price.' },
        { type: 'heading', text: 'Technical inspection before sale' },
        { type: 'paragraph', text: 'Buyers give great importance to technical condition certificates. Get a technical inspection before selling, fix obvious faults.' },
        { type: 'tip', text: 'Faults fixed at low cost (e.g., replacing a fuel filter) can increase the selling price by 500-1000 AZN.' },
        { type: 'heading', text: 'Visual preparation' },
        { type: 'paragraph', text: 'First impression is everything. Professional deep cleaning (body polish, deep interior wash) has a seriously positive effect on the buying-selling process.' },
        { type: 'heading', text: 'Set the right price' },
        { type: 'paragraph', text: 'Research prices of same model cars on platforms like turbo.az, tap.az. Starting 5-10% below average price creates an opportunity for quick sale.' },
        { type: 'heading', text: 'Prepare documents' },
        { type: 'paragraph', text: 'Technical passport, insurance, technical inspection certificate — all of these must be ready. A car with document problems will not sell.' },
      ],
    },
  },
  {
    id: 6,
    title: { az: 'Əyləc sisteminin vacib əlamətləri', ru: 'Важные признаки тормозной системы', en: 'Important signs of brake system issues' },
    excerpt: { az: 'Əyləclərinizin problemi olduğunu necə başa düşərsiniz?...', ru: 'Как понять, что с тормозами проблема?...', en: 'How to understand that your brakes have a problem?...' },
    image: 'https://images.unsplash.com/photo-1558970824-4b19956fa3fa?w=600&q=80',
    category: { az: 'Texniki', ru: 'Технические', en: 'Technical' },
    date: '2026-01-05',
    readTime: 4,
    author: 'Texniki Komanda',
    videoId: 'TbFYIuAIQrw',
    content: {
      az: [
        { type: 'paragraph', text: 'Əyləc sistemi avtomobilin ən kritik təhlükəsizlik sistemidir. Problemin erkən aşkarlanması həyat xilas edir.' },
        { type: 'heading', text: 'Cıqqıltı səsi' },
        { type: 'paragraph', text: 'Əyləc pedalını basdığınızda cıqqıltı eşidirsinizə? Bu, əyləc bəndinərinin bitdiyini bildirən xəbərdarlıq siqnalidir. Dərhal servisa gedin.' },
        { type: 'tip', text: 'Əyləc bəndləri vaxtında dəyişilməzsə, disk zədələnir. Disk dəyişimi bənd dəyişimindən 5-10 dəfə baha başa gəlir.' },
        { type: 'heading', text: 'Vibrasiya' },
        { type: 'paragraph', text: 'Əyləc zamanı sükan titrəyirsə, bu, əyləc diskinin köhnəldiyini və ya deformasiyaya uğradığını göstərir.' },
        { type: 'heading', text: 'Əyləc mayesinin azalması' },
        { type: 'paragraph', text: 'Əyləc mayesi seviyyəsini müntəzəm yoxlayın. Kəskin azalma sızma olduğunu bildirir — bu ciddi təhlükədir.' },
        { type: 'heading', text: 'Pedal aşağı gedir' },
        { type: 'paragraph', text: 'Əyləc pedalı döşəməyə qədər gedirsə, əyləc sistemində hava var deməkdir. Bu vəziyyətdə sürüş etməyin, dərhal yardım çağırın.' },
      ],
      ru: [
        { type: 'paragraph', text: 'Тормозная система — самая критически важная система безопасности автомобиля. Раннее выявление проблемы спасает жизни.' },
        { type: 'heading', text: 'Скрипящий звук' },
        { type: 'paragraph', text: 'Слышите скрип при нажатии на педаль тормоза? Это предупредительный сигнал о том, что тормозные колодки износились. Немедленно обратитесь в сервис.' },
        { type: 'tip', text: 'Если колодки не заменить вовремя, диск повреждается. Замена диска обходится в 5–10 раз дороже замены колодок.' },
        { type: 'heading', text: 'Вибрация' },
        { type: 'paragraph', text: 'Если при торможении руль вибрирует, это говорит о том, что тормозной диск изношен или деформирован.' },
        { type: 'heading', text: 'Снижение уровня тормозной жидкости' },
        { type: 'paragraph', text: 'Регулярно проверяйте уровень тормозной жидкости. Резкое снижение означает утечку — это серьёзная опасность.' },
        { type: 'heading', text: 'Педаль уходит вниз' },
        { type: 'paragraph', text: 'Если педаль тормоза уходит до пола, в тормозной системе есть воздух. В таком случае не езжайте, немедленно вызовите помощь.' },
      ],
      en: [
        { type: 'paragraph', text: 'The brake system is the most critical safety system in a car. Early detection of problems saves lives.' },
        { type: 'heading', text: 'Squealing noise' },
        { type: 'paragraph', text: 'Hearing a squeal when pressing the brake pedal? This is a warning signal that brake pads are worn. Go to a service immediately.' },
        { type: 'tip', text: "If brake pads aren't replaced on time, the disk gets damaged. Disk replacement costs 5-10 times more than pad replacement." },
        { type: 'heading', text: 'Vibration' },
        { type: 'paragraph', text: 'If the steering wheel vibrates when braking, this indicates the brake disk is worn or deformed.' },
        { type: 'heading', text: 'Brake fluid level dropping' },
        { type: 'paragraph', text: 'Check brake fluid level regularly. A sharp drop means there is a leak — this is a serious danger.' },
        { type: 'heading', text: 'Pedal goes to the floor' },
        { type: 'paragraph', text: 'If the brake pedal goes all the way to the floor, there is air in the brake system. Do not drive in this condition, call for help immediately.' },
      ],
    },
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Rəşad M.',
    role: { az: 'Peşəkar Sürücü', ru: 'Профессиональный водитель', en: 'Professional Driver' },
    text: { az: '"Dünən maşının nasosunu dəyişdirməliydim. Platformadan baxdım, yaxınlıqda 3-4 yer var idi. Zəng etdim, qiymət aldım, getdim. 1 saata iş bitdi."', ru: '"Вчера нужно было заменить насос. Посмотрел на платформе, рядом было 3-4 места. Позвонил, узнал цену, поехал. За час всё сделали."', en: '"Yesterday I needed to change the pump. Checked the platform, found 3-4 places nearby. Called, got a quote, went. Done in 1 hour."' },
    rating: 5,
    avatar: 'R',
    color: 'from-blue-500 to-blue-600',
  },
  {
    id: 2,
    name: 'Aqil Ə.',
    role: { az: 'Taksi Sürücüsü', ru: 'Таксист', en: 'Taxi Driver' },
    text: { az: '"Taksi sürürəm, gündə 10+ saat yoldayam. Əvvəl hissə lazım olanda tanışlardan soruşurdum. İndi platformanı açıram, ən yaxın yeri tapıram, bitdi."', ru: '"Езжу на такси, 10+ часов в день. Раньше спрашивал знакомых. Теперь открываю платформу, нахожу ближайшее место, всё."', en: '"I drive a taxi, 10+ hours a day. Used to ask friends. Now I open the platform, find the nearest place, done."' },
    rating: 5,
    avatar: 'A',
    color: 'from-purple-500 to-purple-600',
  },
  {
    id: 3,
    name: 'Amil A.',
    role: { az: 'Yük Maşını Sürücüsü', ru: 'Водитель грузовика', en: 'Truck Driver' },
    text: { az: '"TIR sürücüsüyəm, şəhərlərarası gəzirəm. Yolda qalsam, platformadan həmin ərazidə usta tapıram. Əlaqə nömrəsi var, zəng edirəm. Çox kömək edir."', ru: '"Вожу фуру, межгородские рейсы. Если заглохну в дороге, нахожу мастера через платформу. Есть номер телефона, звоню. Очень помогает."', en: '"I drive a truck, intercity routes. If I break down, I find a master on the platform. There\'s a phone number, I call. Very helpful."' },
    rating: 5,
    avatar: 'Am',
    color: 'from-green-500 to-emerald-600',
  },
]

export const carBrands = [
  { name: 'BMW', logo: '🚗' },
  { name: 'Mercedes', logo: '🚗' },
  { name: 'Toyota', logo: '🚗' },
  { name: 'Honda', logo: '🚗' },
  { name: 'Hyundai', logo: '🚗' },
  { name: 'Kia', logo: '🚗' },
  { name: 'Volkswagen', logo: '🚗' },
  { name: 'Audi', logo: '🚗' },
  { name: 'Ford', logo: '🚗' },
  { name: 'Chevrolet', logo: '🚗' },
  { name: 'Nissan', logo: '🚗' },
  { name: 'Lexus', logo: '🚗' },
  { name: 'Porsche', logo: '🚗' },
  { name: 'Subaru', logo: '🚗' },
  { name: 'Mazda', logo: '🚗' },
  { name: 'Volvo', logo: '🚗' },
]

export const statsData = {
  users: 1240,
  masters: 180,
  services: 95,
  shops: 64,
}